#!groovy
pipeline{
    agent any
    environment{
        HUB="whjmanxe"
        IMAGE="test"
        TAG="latest"
    }
    stages{
        stage('docker build'){
            steps{
                echo "start docker build ${HUB}/${IMAGE}:${TAG}"
                sh "docker build -t ${HUB}/${IMAGE}:${TAG} -f Dockerfile ../"
            }
        }
    }
}